version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build:
      context: ./docker/app
    image: php:7.2-fpm
    container_name: app
    volumes:
      - .:/var/www/html
    # depends_on:
    #   - mysql
#   mysql:
#     image: mysql:5.7
#     container_name: mysql
#     environment:
#       MYSQL_DATABASE: keruhito
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
# volumes:
#   mysql-data: